
Damagelog.weapon_table_default = {
	weapon_jb_deagle = "a Deagle",
	weapon_jb_usp = "an H&K USP",
	weapon_jb_fiveseven = "a Five-Seven",
	weapon_jb_ak47 = "an AK-47",
	weapon_jb_aug = "an AUG",
	weapon_jb_fists = "their Fists",
	weapon_jb_knife = "a Knife",
	weapon_jb_awp = "an AWP",
	weapon_jb_famas = "a Famas",
	weapon_jb_galil = "a Galil",
	weapon_jb_glock = "a Glock",
	weapon_jb_m4a1 = "an M4A1",
	weapon_jb_mac10 = "a Mac 10",
	weapon_jb_mp5navy = "an mp5",
	weapon_jb_p90 = "a P90",
	weapon_jb_scout = "an M40A1",
	weapon_jb_sg552 = "an SG552",
	weapon_jb_tmp = "a TMP(silent)",
	weapon_jb_ump = "a UMP45",
}